//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTPShare.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FTPShareEntities : DbContext
    {
        public FTPShareEntities()
            : base("name=FTPShareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tm_sys_user> tm_sys_user { get; set; }
        public DbSet<td_file> td_file { get; set; }
        public DbSet<td_owner_folder> td_owner_folder { get; set; }
        public DbSet<td_reader_user> td_reader_user { get; set; }
        public DbSet<tm_sys_utype> tm_sys_utype { get; set; }
        public DbSet<tr_reader_folder> tr_reader_folder { get; set; }
    }
}
