//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTPShare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_reader_user
    {
        public td_reader_user()
        {
            this.tr_reader_folder = new HashSet<tr_reader_folder>();
        }
    
        public string owner { get; set; }
        public string reader { get; set; }
        public string pass { get; set; }
        public System.DateTime exp_dt { get; set; }
    
        public virtual ICollection<tr_reader_folder> tr_reader_folder { get; set; }
    }
}
